name: prepare_dataset_force

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install deps
        run: pip install kaggle pillow pycocotools awscli torch ultralytics

      - name: download dataset
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: python py/download_dataset.py

      - name: preprocess
        run: python py/preprocess.py

      - name: archive
        run: |
          tar -czf dataset_processed.tar.gz dataset_processed/
          tar -czf dataset_detection.tar.gz dataset_detection/

      - name: upload to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
          YC_BUCKET_NAME: ${{ secrets.YC_BUCKET_NAME }}
        run: |
          aws s3 cp dataset_processed.tar.gz s3://$YC_BUCKET_NAME/second/cv/dataset_processed.tar.gz \
            --endpoint-url https://storage.yandexcloud.net
          aws s3 cp dataset_detection.tar.gz s3://$YC_BUCKET_NAME/second/cv/dataset_detection.tar.gz \
            --endpoint-url https://storage.yandexcloud.net
